/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulationsIndexRouteImport } from './routes/simulations.index'
import { Route as TestsSlugRouteImport } from './routes/tests.$slug'
import { Route as SimulationsIdRouteImport } from './routes/simulations.$id'
import { Route as OfficeIdRouteImport } from './routes/office.$id'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as SimulationsIdIndexRouteImport } from './routes/simulations.$id.index'
import { Route as SimulationsIdResultsRouteImport } from './routes/simulations.$id.results'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsIndexRoute = SimulationsIndexRouteImport.update({
  id: '/simulations/',
  path: '/simulations/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsSlugRoute = TestsSlugRouteImport.update({
  id: '/tests/$slug',
  path: '/tests/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsIdRoute = SimulationsIdRouteImport.update({
  id: '/simulations/$id',
  path: '/simulations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeIdRoute = OfficeIdRouteImport.update({
  id: '/office/$id',
  path: '/office/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SimulationsIdIndexRoute = SimulationsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SimulationsIdRoute,
} as any)
const SimulationsIdResultsRoute = SimulationsIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => SimulationsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/office/$id': typeof OfficeIdRoute
  '/simulations/$id': typeof SimulationsIdRouteWithChildren
  '/tests/$slug': typeof TestsSlugRoute
  '/simulations/': typeof SimulationsIndexRoute
  '/simulations/$id/results': typeof SimulationsIdResultsRoute
  '/simulations/$id/': typeof SimulationsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/office/$id': typeof OfficeIdRoute
  '/tests/$slug': typeof TestsSlugRoute
  '/simulations': typeof SimulationsIndexRoute
  '/simulations/$id/results': typeof SimulationsIdResultsRoute
  '/simulations/$id': typeof SimulationsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/office/$id': typeof OfficeIdRoute
  '/simulations/$id': typeof SimulationsIdRouteWithChildren
  '/tests/$slug': typeof TestsSlugRoute
  '/simulations/': typeof SimulationsIndexRoute
  '/simulations/$id/results': typeof SimulationsIdResultsRoute
  '/simulations/$id/': typeof SimulationsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/login'
    | '/progress'
    | '/admin'
    | '/api/transcribe'
    | '/api/tts'
    | '/office/$id'
    | '/simulations/$id'
    | '/tests/$slug'
    | '/simulations/'
    | '/simulations/$id/results'
    | '/simulations/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/login'
    | '/progress'
    | '/admin'
    | '/api/transcribe'
    | '/api/tts'
    | '/office/$id'
    | '/tests/$slug'
    | '/simulations'
    | '/simulations/$id/results'
    | '/simulations/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/auth'
    | '/login'
    | '/progress'
    | '/_authenticated/admin'
    | '/api/transcribe'
    | '/api/tts'
    | '/office/$id'
    | '/simulations/$id'
    | '/tests/$slug'
    | '/simulations/'
    | '/simulations/$id/results'
    | '/simulations/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  OfficeIdRoute: typeof OfficeIdRoute
  SimulationsIdRoute: typeof SimulationsIdRouteWithChildren
  TestsSlugRoute: typeof TestsSlugRoute
  SimulationsIndexRoute: typeof SimulationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/': {
      id: '/simulations/'
      path: '/simulations'
      fullPath: '/simulations/'
      preLoaderRoute: typeof SimulationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$slug': {
      id: '/tests/$slug'
      path: '/tests/$slug'
      fullPath: '/tests/$slug'
      preLoaderRoute: typeof TestsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/$id': {
      id: '/simulations/$id'
      path: '/simulations/$id'
      fullPath: '/simulations/$id'
      preLoaderRoute: typeof SimulationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/$id': {
      id: '/office/$id'
      path: '/office/$id'
      fullPath: '/office/$id'
      preLoaderRoute: typeof OfficeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/simulations/$id/': {
      id: '/simulations/$id/'
      path: '/'
      fullPath: '/simulations/$id/'
      preLoaderRoute: typeof SimulationsIdIndexRouteImport
      parentRoute: typeof SimulationsIdRoute
    }
    '/simulations/$id/results': {
      id: '/simulations/$id/results'
      path: '/results'
      fullPath: '/simulations/$id/results'
      preLoaderRoute: typeof SimulationsIdResultsRouteImport
      parentRoute: typeof SimulationsIdRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SimulationsIdRouteChildren {
  SimulationsIdResultsRoute: typeof SimulationsIdResultsRoute
  SimulationsIdIndexRoute: typeof SimulationsIdIndexRoute
}

const SimulationsIdRouteChildren: SimulationsIdRouteChildren = {
  SimulationsIdResultsRoute: SimulationsIdResultsRoute,
  SimulationsIdIndexRoute: SimulationsIdIndexRoute,
}

const SimulationsIdRouteWithChildren = SimulationsIdRoute._addFileChildren(
  SimulationsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
  OfficeIdRoute: OfficeIdRoute,
  SimulationsIdRoute: SimulationsIdRouteWithChildren,
  TestsSlugRoute: TestsSlugRoute,
  SimulationsIndexRoute: SimulationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
